name = "lumikko-api-devel"
main = "src/index.ts"
compatibility_date = "2025-05-25"
workers_dev = false

routes = [{ pattern = "api.lumikko.app/v2beta/*", zone_name = "lumikko.app" }]

[observability.logs]
enabled = false

[vars]
AUTH0_DOMAIN = "neontowel.eu.auth0.com"
AUTH0_AUDIENCE = "https://api.lumikko.app"
